parameters:
  env(DATABASE_URL): ''
  env(DATABASE_USER): 'symfony'
  env(DATABASE_PASSWORD): 'symfony'
  env(DATABASE_NAME): 'stocks_api'
  env(DATABASE_HOST): 'db'
  env(DATABASE_PORT): '3306'
  env(DATABASE_DRIVER): 'mysql'
  env(DATABASE_SERVER_VERSION): '5.6'

doctrine:
  dbal:
    mapping_types:
      enum: string
    dbname: '%env(DATABASE_NAME)%'
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci
    server_version: '%env(DATABASE_SERVER_VERSION)%'
    types:
      uuid: Ramsey\Uuid\Doctrine\UuidType
      enumOrderType: App\Bridge\DBAL\Types\EnumOrderType
      enumSideType: App\Bridge\DBAL\Types\EnumSideType
      enumPositionType: App\Bridge\DBAL\Types\EnumPositionType
      enumSourceClassType: App\Bridge\DBAL\Types\EnumSourceClassType

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    filters:
      softdeleteable:
        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
        enabled: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
