# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    serializer:
      enabled: true
      enable_annotations: true
      mapping:
        paths: [ '%kernel.project_dir%/config/serialization' ]
    validation:
      enabled: true
      mapping:
        paths: [ '%kernel.project_dir%/config/validation' ]

    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true