gesdinet_jwt_refresh_token:
    ttl: 86400
    ttl_update: true
    user_identity_field: guid
    token_parameter_name: refreshToken
    user_provider: security.user.provider.concrete.app_user_provider
