framework:
  messenger:
    buses:
      messenger.bus.default:
        default_middleware: true
        middleware:
          - 'App\Message\Job\Middleware\JobMiddleware'
          - 'App\Message\Job\Middleware\JobItemMiddleware'
    failure_transport: failed
    transports:
      failed: 'doctrine://default?queue_name=failed'
      async:
        dsn:  "%env(MESSENGER_TRANSPORT_DSN)%jobs"
        options:
          queues:
            jobs_processing: ~
          exchange:
            name: amq.fanout
            type: fanout
      source:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%info"
        options:
          queues:
            source_messages:
              binding_keys:
                - source.command.*
                - source.*.command
            source_updates:
              binding_keys:
                - source.*.info
                - source.*.status
            source_errors:
              binding_keys:
                - source.*.error
            source_orders:
              binding_keys:
                - source.*.order
          exchange:
            name: amq.topic
            type: topic
      app:
        dsn: "%env(MESSENGER_TRANSPORT_DSN)%updates"
        options:
          queues:
            notify:
              binding_keys:
                - notifiy.info.*
                - notifiy.error.*
                - notifiy.command.*
                - job.*.info
            web:
              binding_keys:
                - web.*.info
                - job.*.info
          exchange:
            name: amq.topic
            type: topic
    routing:
      App\Message\Job\JobStatusMessage: app
      App\Message\Job\JobItemStatusMessage: app
      'App\Message\SyncOrderHistoryMessage': async
      'App\Message\SyncOrdersRequestMessage': async
      'App\Message\SyncTickersRequestMessage': async
      'App\Message\SyncTickerMessage': async