framework:
    messenger:
        buses:
            messenger.bus.default:
                default_middleware: true
                middleware:
                    - 'App\Message\Job\Middleware\JobMiddleware'
                    - 'App\Message\Job\Middleware\JobItemMiddleware'
        transports:
            job:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%job.fifo'
                options:
                    access_key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret_key: '%env(AWS_SECRET_ACCESS_KEY)%'
                    account: '%env(AWS_ACCOUNT)%'
                    endpoint: '%env(SQS_QUEUE_ENDPOINT)%'
                    region: '%env(AWS_REGION)%'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%async.fifo'
                options:
                    access_key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret_key: '%env(AWS_SECRET_ACCESS_KEY)%'
                    account: '%env(AWS_ACCOUNT)%'
                    endpoint: '%env(SQS_QUEUE_ENDPOINT)%'
                    region: '%env(AWS_REGION)%'
            orders:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%orders.fifo'
                options:
                    access_key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret_key: '%env(AWS_SECRET_ACCESS_KEY)%'
                    account: '%env(AWS_ACCOUNT)%'
                    endpoint: '%env(SQS_QUEUE_ENDPOINT)%'
                    region: '%env(AWS_REGION)%'
            app:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%app'
                options:
                    access_key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret_key: '%env(AWS_SECRET_ACCESS_KEY)%'
                    account: '%env(AWS_ACCOUNT)%'
                    endpoint: '%env(SQS_QUEUE_ENDPOINT)%'
                    region: '%env(AWS_REGION)%'
        routing:
            App\Message\ApplicationMessage: app
            App\Message\SyncOrdersRequestMessage: job
            App\Message\SyncOrderHistoryMessage: async
            App\Message\SyncTickersRequestMessage: job
            App\Message\SyncTickerMessage: async