version: '3'

services:
  stocks-api-php:
#    build:
#      context: ./docker/php-fpm
#      dockerfile: Dockerfile
##      args:
#        - JWT_PASSPHRASE=${JWT_PASSPHRASE}
    image: 448507992616.dkr.ecr.us-west-2.amazonaws.com/stocks-api-php-fpm:latest
    container_name: ${DOCKER_RUNNING_IMAGE_NAME}
    volumes:
        - .:/opt/app-root/src
        - ./logs/symfony:/opt/app-root/src/var/log
        - ./docker/php-fpm/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    links:
      - stocks-api-database
    env_file:
      - .env

  stocks-api-nginx:
#    build: ./docker/nginx
    image: 448507992616.dkr.ecr.us-west-2.amazonaws.com/stocks-api-nginx
    container_name: ${DOCKER_RUNNING_IMAGE_NAME}-nginx
    ports:
        - ${NGINX_PORT}8080
    links:
        - stocks-api-php
    volumes:
        - .:/opt/app-root/src
        - ./logs/nginx:/var/log/nginx

  stocks-api-database:
    image: mysql:latest
    container_name: ${DOCKER_RUNNING_IMAGE_NAME}-mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
        - ${MYSQL_IMAGE_PORT}3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  stocks-api-redis:
    image: redis
    container_name: ${DOCKER_RUNNING_IMAGE_NAME}-redis
    ports:
      - 6379:6379

  stocks-api-redis-commander:
    image: rediscommander/redis-commander
    ports:
      - 8081:8081
    environment:
      REDIS_HOST: 'stocks-api-redis'
