sudo: required

language: bash

services:
  - docker

script:
  - cp config/satis.json.dist config/satis.json
  - cp config/parameters.satisfy.yml.dist config/parameters.satisfy.yml
  - bash tests.sh
