App\Entity\Account:
  attributes:
    guid:
      groups:
        - account.get
    accountInfo:
      groups:
        - account.get
    accountStatusType:
      groups:
        - account.get
        - account.post
        - account.put
    apiEndpointUrl:
      groups:
        - account.get
        - account.post
        - account.put
    apiKey:
      groups:
        - account.get
        - account.post
        - account.put
    apiSecret:
      groups:
        - account.get
        - account.post
        - account.put
    brokerage:
      groups:
        - account.get
        - account.post
    description:
      groups:
        - account.get
        - account.post
        - account.put
    name:
      groups:
        - account.get
        - account.post
        - account.put
    jobs:
      groups:
        - account.get
    orders:
      groups:
        - account.get
    positions:
      groups:
        - account.get
    users:
      groups:
        - account.get
        - account.post
        - account.put
    createdAt:
      groups:
        - account.get
    createdBy:
      groups:
        - account.get
    modifiedAt:
      groups:
        - account.get
    modifiedBy:
      groups:
        - account.get
    deactivatedAt:
      groups:
        - account.get
    deactivatedBy:
      groups:
        - account.get
