App\DTO\Brokerage\AccountInfoInterface:
  discriminator_map:
    type_property: brokerage
    mapping:
      alpaca: 'App\DTO\Brokerage\Alpaca\AlpacaAccountInfo'
      td_ameritrade: 'App\DTO\Brokerage\TdAmeritrade\TdAmeritradeAccountInfo'