App\DTO\Brokerage\Alpaca\AlpacaPosition:
  attributes:
    assetId:
      groups:
        - position.get
        - account.get
    avgEntryPrice:
      groups:
        - position.get
    changeToday:
      groups:
        - position.get
        - account.get
    costBasis:
      group:
        - position.get
    currentPrice:
      groups:
        - position.get
        - account.get
    exchange:
      groups:
        - position.get
    lastDayPrice:
      groups:
        - position.get
    marketValue:
      groups:
        - position.get
        - account.get
    qty:
      groups:
        - position.get
        - account.get
    side:
      groups:
        - position.get
        - account.get
    symbol:
      groups:
        - position.get
        - account.get
    unrealizedPl:
      groups:
        - position.get
    unrealizedPlpc:
      groups:
        - position.get
    unrealizedIntradayPl:
      groups:
        - position.get
