App\DTO\Brokerage\Alpaca\AccountInfo:
  attributes:
    id:
      groups:
        - account.get
        - account_info.get
    accountBlocked:
      groups:
        - account.get
        - account_info.get
    accountNumber:
      groups:
        - account.get
        - account_info.get
    brokerage:
      groups:
        - account.get
        - account_info.get
    buyingPower:
      groups:
        - account.get
        - account_info.get
    cash:
      groups:
        - account.get
        - account_info.get
    createdAt:
      groups:
        - account.get
        - account_info.get
    currency:
      groups:
        - account.get
        - account_info.get
    daytradingBuyingPower:
      groups:
        - account.get
        - account_info.get
    daytradeCount:
      groups:
        - account.get
        - account_info.get
    equity:
      groups:
        - account.get
        - account_info.get
    initialMargin:
      groups:
        - account.get
        - account_info.get
    lastEquity:
      groups:
        - account.get
        - account_info.get
    lastMaintenanceMargin:
      groups:
        - account.get
        - account_info.get
    longMarketValue:
      groups:
        - account.get
        - account_info.get
    maintenanceMargin:
      groups:
        - account.get
        - account_info.get
    multiplier:
      groups:
        - account.get
        - account_info.get
    patternDayTrader:
      groups:
        - account.get
        - account_info.get
    portfolioValue:
      groups:
        - account.get
        - account_info.get
    regtBuyingPower:
      groups:
        - account.get
        - account_info.get
    shortMarketValue:
      groups:
        - account.get
        - account_info.get
    shortingEnabled:
      groups:
        - account.get
        - account_info.get
    sma:
      groups:
        - account.get
        - account_info.get
    status:
      groups:
        - account.get
        - account_info.get
    tradeSuspendedByUser:
      groups:
        - account.get
        - account_info.get
    tradingBlocked:
      groups:
        - account.get
        - account_info.get
    transfersBlocked:
      groups:
        - account.get
        - account_info.get