App\Entity\Order:
  attributes:
    guid:
      groups:
        - order.get
    account:
      groups:
        - order.get
        - order.post
        - order.put
    orderInfo:
      groups:
        - order.get
        - order.post
        - order.put
    orderStatusType:
      groups:
        - order.get
        - order.post
        - order.put
    orderType:
      groups:
        - order.get
        - order.post
        - order.put
    position:
      groups:
        - order.get
        - order.post
        - order.put
    source:
      groups:
        - order.get
        - order.post
    symbol:
      groups:
        - order.get
        - order.post
    createdAt:
      groups:
        - order.get
    createdBy:
      groups:
        - order.get
    modifiedAt:
      groups:
        - order.get
    modifiedBy:
      groups:
        - order.get
    deactivatedAt:
      groups:
        - order.get
    deactivatedBy:
      groups:
        - order.get
