App\Entity\Position:
  attributes:
    guid:
      groups:
        - position.get
    account:
      groups:
        - position.get
    brokerage:
      groups:
        - position.get
    order:
      groups:
        - position.get
    qty:
      groups:
        - position.get
    side:
      groups:
        - position.get
    symbol:
      groups:
        - position.get
    createdAt:
      groups:
        - position.get
    createdBy:
      groups:
        - position.get
    modifiedAt:
      groups:
        - position.get
    modifiedBy:
      groups:
        - position.get
    deactivatedAt:
      groups:
        - position.get
    deactivatedBy:
      groups:
        - position.get
