App\Entity\TickerType:
  attributes:
    guid:
      groups:
        - ticker_type.get
    name:
      groups:
        - ticker_type.get
        - ticker_type.post
        - ticker_type.put
    code:
      groups:
        - ticker_type.get
        - ticker_type.post
        - ticker_type.put
    createdAt:
      groups:
        - ticker_type.get
    createdBy:
      groups:
        - ticker_type.get
    modifiedAt:
      groups:
        - ticker_type.get
    modifiedBy:
      groups:
        - ticker_type.get
    deactivatedAt:
      groups:
        - ticker_type.get
    deactivatedBy:
      groups:
        - ticker_type.get

