App\Entity\User:
  attributes:
    guid:
      groups:
        - user.get
    username:
      groups:
        - account.get
        - user.get
        - user.post
        - user.put
    avatar:
      groups:
        - user.get
        - user.post
        - user.put
    firstName:
      groups:
        - user.get
        - user.post
        - user.put
    lastName:
      groups:
        - user.get
        - user.post
        - user.put
    email:
      groups:
        - user.get
        - user.post
        - user.put
    phone:
      groups:
        - user.get
        - user.post
        - user.put
    description:
      groups:
        - user.get
        - user.post
        - user.put
    accounts:
      groups:
        - user.get
        - user.post
        - user.put
    jobs:
      groups:
        - user.get
    createdAt:
      groups:
        - user.get
    createdBy:
      groups:
        - user.get
    modifiedAt:
      groups:
        - user.get
    modifiedBy:
      groups:
        - user.get
    deactivatedAt:
      groups:
        - user.get
    deactivatedBy:
      groups:
        - user.get
    plainPassword:
      groups:
        - user.get
        - user.put
        - user.post
