resources:
  App\Entity\Account:
    attributes:
      normalization_context:
        groups: [ 'account.get' ]
      denormalization_context:
        groups: [ 'account.post' ]

    collectionOperations:
      get:
        method: GET
      post:
        method: POST

      account_history:
        method: GET
        path: /account/{id}/account_history
        force_eager: false
        defaults:
          _api_resource_context:
            identifiers:
              - [ id, App\Entity\Account, true ]
        normalization_context:
          groups: [ order_info.get ]
        swagger_context:
          summary: Get account history from a brokerage
          tags: [ Account ]
          parameters:
            - name: id
              in: path
              required: true

      get_account_positions:
        method: GET
        path: '/accounts/{id}/positions'
        output: App\DTO\Brokerage\Alpaca\Position
        defaults:
          _api_subresource_context:
            identifiers:
              - [ id, App\Entity\Account, true ]
        normalization_context:
          groups: [ 'position.get' ]
        swagger_context:
          summary: Get open positions for account
          tags: [ Account ]
          parameters:
            - name: id
              in: path
              required: true
              type: string

    itemOperations:
      get:
        method: GET

      account_get_position:
        method: GET
        path: /accounts/{id}/positions/{symbol}
        defaults:
          _api_subresource_context:
            - [ id, App\Entity\Account, true ]
            - [ symbol, App\Entity\Ticker, true ]
        normalization_context:
          groups: [ 'position.get' ]
        swagger_context:
          summary: Get open position for action
          tags: [ Account ]
          paramaters:
            - name: id
              in: path
              required: true
              type: string
            - name: symbol
              in: path
              required: true
              type: string
      put:
        method: PUT
      delete:
        method: DELETE

    properties:
      id:
        identifier: false
      guid:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'