resources:
  App\DTO\Brokerage\Alpaca\AlpacaPositionInfo:
    atrributes:
      normalization_context:
        groups: ['alpaca_position_info.get']
      order: {modifiedAt: DESC, id: DESC}

    itemOperations:
      get:
        method: GET
        controller: App\Controller\DummyController

    collectionOperations: ~

    properties:
      id:
        identifier: true
