resources:
  App\DTO\Brokerage\Alpaca\AlpacaAccountInfo:
    atrributes:
      denormalization_context:
        groups: [ 'alpaca_account_info.get' ]
      normalization_context:
        groups: [ 'alpaca_account_info.get' ]
      order: {modifiedAt: DESC, id: DESC}

    itemOperations: ~

    collectionOperations: ~
    
    properties:
      id:
        identifier: true
