resources:
  App\DTO\Brokerage\Alpaca\AlpacaAccountInfo:
    atrributes:
      normalization_context:
        groups: ['alpaca_alpaca_account_info.get']

    itemOperations: 
      get:
        method: GET
        controller: App\Controller\DummyController
        
    collectionOperations: ~
    
    properties:
      id:
        identifier: true
