resources:
  App\DTO\Brokerage\Alpaca\Order\AlpacaOrderInfo:
    atrributes:
      normalization_context:
        groups: ['alpaca_order_info.get']
      order: {modifiedAt: DESC, id: DESC}

    itemOperations:
      get:
        method: GET
        controller: 'App\Controller\DummyController'

    properties:
      id:
        identifier: true
