resources:
  App\Entity\Brokerage:
    attributes:
      normalization_context:
        groups: [ 'brokerage.get' ]

    collectionOperations:
      get:
        method: GET

    itemOperations:
      get:
        method: GET

    properties:
      id:
        identifier: false
      guid:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'
