resources:
  App\Entity\Job:
    attributes:
      normalization_context:
        groups: [ 'job.get' ]
      denormalization_context:
        groups: [ 'job.post' ]

    collectionOperations:
        get:
          method: GET
        post:
          method: POST

    itemOperations:
      get:
        method: GET
      put:
        method: PUT
      delete:
        method: DELETE

    properties:
      id:
        identifier: true
