resources:
  App\Entity\Job:
    attributes:
      filters:
        - job.search_filter
        - job.order_filter
      normalization_context:
        groups: [ 'job.get' ]
      denormalization_context:
        groups: [ 'job.post' ]
      order: {modifiedAt: DESC, id: DESC}

    collectionOperations:
      get:
        method: GET

    itemOperations:
      get:
        method: GET

      cancel_job_request:
        method: GET
        path: jobs/{id}/cancel
        input: App\DTO\CancelJobRequest
        output: App\Entity\Job
        force_eager: true
        defaults:
          _api_resource_context:
            identifiers:
              - [ id, App\Entity\Job, true ]
        normalization_context:
          groups: [ job.get ]
        swagger_context:
          summary: Cancel job
          tags: [ Job ]
          parameters:
            - name: id
              in: path
              required: true
          responses:
            200:
              description: "Job Cancelled"
            400:
              description: "Job Cancel Failed"
            401:
              description: "Unauthorized"
            404:
              description: "Job not found"
      put:
        method: PUT
      delete:
        method: DELETE

    properties:
      id:
        identifier: false
      guid:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'