resources:
  App\Entity\JobItem:
    attributes:
      normalization_context:
        groups: [ 'job_item.get' ]
      denormalization_context:
        groups: [ 'job_item.post' ]
      order: {modifiedAt: DESC, id: DESC}

    collectionOperations:
      get:
        method: GET

    itemOperations:
      get:
        method: GET
      delete:
        method: DELETE

    properties:
      id:
        identifier: false
      guid:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'
