resources:
  App\DTO\Aws\Sns\Notification:
    attributes:
      normalization_context:
        groups: [ 'notification.get' ]
      denormalization_context:
        groups: [ 'notification.post' ]

    collectionOperations:
      listen:
        method: POST
        path: /topics/listen
        output: App\DTO\Aws\Sns\Notification
        swagger_context:
          summary: Topic Notification Listener Endpoint
          tags: [ Topic ]

    properties:
      id:
        identifier: false
      messageId:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'