resources:
  App\Entity\Order:
    attributes:
      normalization_context:
        groups: [ 'order.get' ]
      denormalization_context:
        groups: [ 'order.post' ]

    collectionOperations:
      get:
        method: GET
      post:
        method: POST

      account_sync_orders:
        method: GET
        path: /account/{id}/sync_orders
        force_eager: false
        defaults:
          _api_subresource_context:
            identifiers:
              - [ id, App\Entity\Account, true]
        normalization_context:
          groups: [ order_info.get ]
        swagger_context:
          summary: Sync account orders from a brokerage
          tags: [ Account ]
          parameters:
            - name: id
              in: path
              required: true

    itemOperations:
      get:
        method: GET
      put:
        method: PUT
      delete:
        method: DELETE

    properties:
      id:
        identifier: false
      guid:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'
