resources:
  App\Entity\OrderType:
    attributes:
      normalization_context:
        groups: [ 'order_type.get' ]
      denormalization_context:
        groups: [ 'order_type.post' ]

    collectionOperations:
        get:
          method: GET
        post:
          method: POST

    itemCollections:
      get:
        method: GET
      put:
        method: PUT
      delete:
        method: DELETE

    properties:
      id:
        identifier: true
