resources:
  App\DTO\Aws\Sns\PublishMessageRequest:
    attributes:
      normalization_context:
        groups: [ 'publish_message_request.get' ]
      denormalization_context:
        groups: [ 'publish_message_request.post' ]

    collectionOperations:
      publish:
        method: POST
        path: /topics/publish
        input: App\DTO\Aws\Sns\PublishMessageRequest
        output: App\DTO\Aws\Sns\PublishMessageResponse
        normalization_context:
          groups: [ 'publish_message_response.get' ]
        denormalization_context:
          groups: [ 'publish_message_request.post' ]
        swagger_context:
          summary: Publish Notification
          tags: [ Topic ]

    properties:
      id:
        identifier: false
      guid:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'