resources:
  App\DTO\SyncTickersRequest:
    attributes:
      normalization_context:
        groups: [ 'sync_tickers_request.get' ]
      denormalization_context:
        groups: [ 'sync_tickers_request.post' ]

    collectionOperations:
      post:
        method: POST
        path: tickers/sync_tickers
        output: App\Entity\Job
        normalization_context:
          groups: [ job.get ]
        swagger_context:
          summary: Sync tickers orders from a brokerage
          tags: [ Ticker ]
          responses:
            200:
              description: 'Job Initiated'
            400:
              description: "Job Failed"
            401:
              description: "Unauthorized"
            404:
              description: "AlpacaAccount not found"

    properties:
      id:
        identifier: false
      guid:
        identitier: true