resources:
  App\DTO\SyncOrdersRequest:
    attributes:
      normalization_context:
        groups: [ 'sync_orders_request.get' ]
      denormalization_context:
        groups: [ 'sync_orders_request.post' ]

    collectionOperations:
      post:
        method: POST
        path: accounts/sync_orders
        output: App\Entity\Job
        normalization_context:
          groups: [ job.get ]
        swagger_context:
          summary: Sync account orders from a brokerage
          tags: [ Account ]
          responses:
            200:
              description: 'Job Initiated'
            400:
              description: "Job Failed"
            401:
              description: "Unauthorized"
            404:
              description: "Account not found"

    properties:
      id:
        identifier: false
      guid:
        identitier: true