resources:
  App\DTO\Brokerage\TdAmeritrade\TdAmeritradeAccountInfo:
    atrributes:
      denormalization_context:
        groups: [ 'td_ameritrade_account_info.get' ]
      normalization_context:
        groups: [ 'td_ameritrade_account_info.get' ]
      order: { modifiedAt: DESC, id: DESC }

    itemOperations: ~

    collectionOperations: ~

    properties:
      id:
        identifier: true