resources:
  App\Entity\TickerSector:
    attributes:
      normalization_context:
        groups: [ 'ticker_sector.get' ]
      denormalization_context:
        groups: [ 'ticker_sector.post' ]
      order: {modifiedAt: DESC, id: DESC}

    collectionOperations:
      get:
        method: GET
      post:
        method: POST

    itemOperations:
      get:
        method: GET
      put:
        method: PUT
      delete:
        method: DELETE

    properties:
      id:
        identifier: true

