resources:
  App\Entity\User:
    attributes:
      normalization_context:
        groups: [ 'user.get' ]
      denormalization_context:
        groups: [ 'user.post' ]

    collectionOperations:
        get:
          method: GET
        post:
          method: POST

    itemOperations:
      get:
        method: GET
      put:
        method: PUT
      delete:
        method: DELETE

    properties:
      id:
        identifier: false
      guid:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'
