resources:
  App\Entity\User:
    attributes:
      normalization_context:
        groups: [ 'user.get' ]
      denormalization_context:
        groups: [ 'user.post', 'user.put' ]
      order: {modifiedAt: DESC, id: DESC}

    collectionOperations:
        get:
          method: GET
          security: 'is_granted("ROLE_ADMIN")'
        post:
          method: POST
          security: 'is_granted("ROLE_ADMIN")'

    itemOperations:
      get:
        method: GET
        security: 'is_granted("ROLE_ADMIN") or object === user'
      put:
        method: PUT
        security: 'is_granted("ROLE_ADMIN") or object === user'
      delete:
        method: DELETE
        security: 'is_granted("ROLE_ADMIN") or object === user'

    properties:
      id:
        identifier: false
      guid:
        identifier: true
        swagger_context:
          example: 'd6f68382-dd82-4324-b04c-89266d70ee2a'
