services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    App\Tests\Behat\DatabaseContext: ~

#    App\Tests\Behat\ExtendedJsonContext:
#        arguments:
#            $httpCallResultPool: '@behatch.http_call.result_pool'

    App\Tests\Behat\FixtureContext:
        arguments:
            $entityManager: '@doctrine.orm.default_entity_manager'

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
