services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true
        bind:
            $kernel: '@kernel'

    App\Tests\Behat\DatabaseContext: ~

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
