services:
  ticker.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments:
      - name: 'ipartial'
        ticker: 'ipartial'
        market: 'exact'
    tags: [ 'api_platform.filter' ]

  ticker.relation_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments:
      - sector.name: 'exact'
    tags: [ 'api_platform.filter' ]

  ticker.or_search_filter:
    parent: 'stocks_api.api_platform.orm.or_search_filter'
    arguments:
      $properties:
        name: ipartial
        ticker: ipartial
      $propertySearchName: search
    tags: [ 'api_platform.filter' ]
