services:
  topic.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments:
      - name: 'ipartial'
    tags: [ 'api_platform.filter' ]

  topic.order_filter:
    parent: 'api_platform.doctrine.orm.order_filter'
    arguments:
      - name: ~
        topic: ~
    tags: [ 'api_platform.filter' ]