App\Entity\Brokerage:
  attributes:
    guid:
      groups:
        - brokerage.get
    name:
      groups:
        - brokerage.get
    description:
      groups:
        - brokerage.get
    url:
      groups:
        - brokerage.get
    apiDocumentUrl:
      groups:
        - brokerage.get
    accounts:
      groups:
        - brokerage.get
    orders:
      groups:
        - brokerage.get
    createdAt:
      groups:
        - brokerage.get
    createdBy:
      groups:
        - brokerage.get
    modifiedAt:
      groups:
        - brokerage.get
    modifiedBy:
      groups:
        - brokerage.get
    deactivatedAt:
      groups:
        - brokerage.get
    deactivatedBy:
      groups:
        - brokerage.get
